# Generated by Django 2.0.2 on 2018-02-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('password', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=1000)),
                ('entries', models.IntegerField()),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(max_length=1000)),
                ('password', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=1000)),
                ('entries', models.IntegerField()),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
