# Generated by Django 2.0.2 on 2018-02-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protected_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='entries',
            field=models.IntegerField(default=0),
        ),
    ]
