# Generated by Django 2.0.2 on 2018-02-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protected_links', '0002_auto_20180206_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='entries',
            field=models.IntegerField(default=0),
        ),
    ]
