# Generated by Django 2.0.2 on 2018-02-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protected_links', '0003_auto_20180206_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
