# Generated by Django 2.0.2 on 2018-02-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protected_links', '0005_auto_20180206_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='user_agent',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='links',
            name='user_agent',
            field=models.CharField(default='', max_length=100),
        ),
    ]
